tap "dunn/emacs"
tap "ethanholen/taps"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/test-bot"
tap "iina/mpv-iina"
tap "jakehilborn/jakehilborn"
tap "jakevossen5/taps"
tap "louisbrunner/valgrind"
tap "twilio/brew"
brew "node"
brew "angular-cli"
brew "python@3.9"
brew "autojump"
brew "automake"
brew "carthage"
brew "cmatrix"
brew "cocoapods"
brew "cowsay"
brew "sfml"
brew "csfml"
brew "docutils"
brew "exa"
brew "fortune"
brew "fzf"
brew "gcc"
brew "pkg-config"
brew "go"
brew "gotop"
brew "grip"
brew "halibut"
brew "howdoi"
brew "htop"
brew "hyperkit"
brew "jq"
brew "kubernetes-cli"
brew "macvim"
brew "make"
brew "mas"
brew "minikube"
brew "mono", link: false
brew "nasm"
brew "neofetch"
brew "openjdk"
brew "pandoc"
brew "pyenv"
brew "screenfetch"
brew "switchaudio-osx"
brew "texi2html"
brew "tldr"
brew "uchardet"
brew "watchman"
brew "watson"
brew "wget"
brew "wifi-password"
brew "yarn"
brew "youtube-dl"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "ethanholen/taps/rdme-gen"
brew "iina/mpv-iina/ffmpeg-iina"
brew "jakehilborn/jakehilborn/displayplacer"
brew "jakevossen5/taps/check-for-homebrew-alternatives"
brew "jakevossen5/taps/pi-generator-from-blocks"
brew "jakevossen5/taps/watson-vis"
brew "louisbrunner/valgrind/valgrind", args: ["HEAD"]
brew "twilio/brew/twilio"
cask "1password"
cask "adguard"
cask "alfred"
cask "appcleaner"
cask "balenaetcher"
cask "bartender"
cask "bitbar"
cask "blender"
cask "brave-browser"
cask "deluge"
cask "discord"
cask "docker"
cask "dropbox"
cask "duet"
cask "emacs"
cask "firefox"
cask "fluid"
cask "github"
cask "gitkraken"
cask "go2shell"
cask "google-chrome"
cask "handbrake"
cask "intellij-idea"
cask "istat-menus"
cask "iterm2"
cask "java"
cask "kap"
cask "karabiner-elements"
cask "keyboard-maestro"
cask "kindle"
cask "macdown"
cask "mactex-no-gui"
cask "makemkv"
cask "mono-mdk-for-visual-studio"
cask "nordvpn"
cask "notion"
cask "nvalt"
cask "obsidian"
cask "omnifocus"
cask "pastebot"
cask "plex"
cask "pocket-casts"
cask "postman"
cask "rocket"
cask "selfcontrol"
cask "slack"
cask "spotify"
cask "steam"
cask "toggl"
cask "unity-hub"
cask "virtualbox"
cask "visual-studio"
cask "visual-studio-code"
cask "vlc"
cask "zsa-wally"
mas "Bear", id: 1091189122
mas "CodeRunner", id: 955297617
mas "DaisyDisk", id: 411643860
mas "Day One", id: 1055511498
mas "Drafts", id: 1435957248
mas "Fantastical", id: 975937182
mas "Front and Center", id: 1493996622
mas "Gestimer", id: 990588172
mas "GoodNotes", id: 1444383602
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Parcel", id: 639968404
mas "Spark", id: 1176895641
mas "SwitchGlass", id: 1498546559
mas "Termius", id: 1176074088
mas "TweetDeck", id: 485812721
mas "Vimari", id: 1480933944
mas "Xcode", id: 497799835
