#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings

# layout
yabai -m config   layout                       bsp

yabai -m config   window_placement             second_child


# Padding
yabai -m config   top_padding                  4
yabai -m config   bottom_padding               4
yabai -m config   left_padding                 4
yabai -m config   right_padding                4
yabai -m config   window_gap                   4



# Mouse Settings
yabai -m config   mouse_follows_focus         off

yabai -m config   mouse_modifier               alt
yabai -m config   mouse_action1                move
yabai -m config   mouse_action2                resize
yabai -m config   mouse_drop_action            swap



# Unmanaged Apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^iTerm2$" manage=on
yabai -m rule --add app="^Microsoft Teams$" manage=off
yabai -m rule --add app="^DaisyDisk$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Pulse Secure$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Messages$" manage=off

# yabai -m config   window_origin_display        default
# yabai -m config   window_zoom_persist          on
# yabai -m config   window_topmost               off
# yabai -m config   window_shadow                on
# yabai -m config   window_animation_duration    0.0
# yabai -m config   window_animation_frame_rate  120
# yabai -m config   window_opacity_duration      0.0
# yabai -m config   active_window_opacity        1.0
# yabai -m config   normal_window_opacity        0.90
# yabai -m config   window_opacity               off
# yabai -m config   insert_feedback_color        0xffd75f5f
# yabai -m config   active_window_border_color   0xffff
# yabai -m config   normal_window_border_color   0xff555555
# yabai -m config   window_border_width          4
# yabai -m config   window_border_radius         12
# yabai -m config   window_border_blur           off
# yabai -m config   window_border_hidpi          on
# yabai -m config   window_border                off
# yabai -m config   split_ratio                  0.50
# yabai -m config   split_type                   auto
# yabai -m config   auto_balance                 off



echo "yabai configuration loaded.."
